#!/usr/bin/env python3

import sys
import os

# Get the absolute path to the project root directory
project_root = os.path.dirname(os.path.abspath(__file__))

# Add the 'src' directory to the Python path
sys.path.insert(0, os.path.join(project_root, 'src'))

from src.main import main

if __name__ == "__main__":
    main()
