info = {"message": "update cuda", "commit": "51b382e11697d3d435cb376101068c34871f494c", "date": "2023/08/24 12:01:20", "branch": "main", "version": "51b382e+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
