trigger:
  # branches:
  #   include:
  #   - main
  paths:
    exclude:
      - labeldata_studio/*
      - ../*


variables:
- name: kubernetesServiceConnection 
  value: 'dev'

stages:
- stage: ScaleUpMultiGpuNode
  jobs:
  - job: Scale_UP_GPUS
    steps:
      - task: AWSShellScript@1
        displayName: AWS-ScaleUp
        inputs:
          awsCredentials: 'AWS-Presight'
          regionName: 'eu-west-1'
          scriptType: 'inline'
          inlineScript: 'aws autoscaling update-auto-scaling-group --region eu-west-1 --auto-scaling-group-name eks-gpuNodeGroup-01-fec25476-65a4-55b1-0f39-a3d58239e126 --launch-template LaunchTemplateId=lt-06134c60a2a05717c,Version=11 --desired-capacity 1'